name: core_environment
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.7.2 <4.0.0"
  flutter: ">=3.29.3"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.27.7
  intl: ^0.19.0
  collection: ^1.16.0
  country_flags: ^3.0.0
  equatable: ^2.0.5
  flutter_timezone: ^4.1.1
  timeago: ^3.7.0
  permission_handler: ^11.3.1
  change_case: ^2.2.0
  package_info_plus: ^8.3.0

  # library
  service_locator:
    path: ../../library/service_locator

  # core
  core_analytics:
    path: ../../core/core_analytics
  core_storage:
    path: ../../core/core_storage

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.4
  file: ^7.0.0
