name: ui_common
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.7.2 <4.0.0"
  flutter: ">=3.29.3"

dependencies:
  flutter:
    sdk: flutter
  expandable: ^5.0.1
  responsive_framework: ^1.0.0
  intersperse: ^2.0.0
  sliver_tools: ^0.2.12
  equatable: ^2.0.5
  collection: ^1.16.0
  expansion_tile_group: ^2.1.0
  autoscale_tabbarview: ^1.0.2
  share_plus: ^11.0.0
  cached_network_image: ^3.4.1
  super_paging:
    git:
      url: https://github.com/robzimpulse/super_paging.git
      ref: paging-sliver-grid

  # entity
  entity_manga:
    path: ../../entity/entity_manga

  # core
  core_analytics:
    path: ../../core/core_analytics
  core_route:
    path: ../../core/core_route
  core_environment:
    path: ../../core/core_environment
  core_storage:
    path: ../../core/core_storage
  core_network:
    path: ../../core/core_network

  # library
  safe_bloc:
    path: ../../library/safe_bloc
  service_locator:
    path: ../../library/service_locator
  manga_dex_api:
    path: ../../library/manga_dex_api

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
