name: core_storage
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.7.2 <4.0.0"
  flutter: ">=3.29.3"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3
  flutter_cache_manager: ^3.3.1
  path_provider: ^2.1.4
  filesystem_picker: ^4.1.0
  rxdart: ^0.27.7
  file: ^7.0.0
  path: ^1.9.0
  dio: ^5.7.0
  universal_io: ^2.2.2
  permission_handler: ^11.3.1

  service_locator:
    path: ../../library/service_locator
  manga_service_drift:
    path: ../../library/manga_service_drift

  # core
  core_analytics:
    path: ../../core/core_analytics
  core_network:
    path: ../../core/core_network

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
