name: domain_manga
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.7.2 <4.0.0"
  flutter: ">=3.29.3"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.16.0
  rxdart: ^0.27.7
  html: ^0.15.5
  universal_io: ^2.2.2
  file: ^7.0.0

  # core
  core_analytics:
    path: ../../core/core_analytics
  core_network:
    path: ../../core/core_network
  core_environment:
    path: ../../core/core_environment
  core_storage:
    path: ../../core/core_storage

  # entity
  entity_manga:
    path: ../../entity/entity_manga

  # library
  service_locator:
    path: ../../library/service_locator
  manga_dex_api:
    path: ../../library/manga_dex_api

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
