name: core_network
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.7.2 <4.0.0"
  flutter: ">=3.29.3"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  dio_smart_retry: ^6.0.0
  mutex: ^3.1.0
  universal_io: ^2.2.2
  flutter_inappwebview: ^6.1.0
  html: ^0.15.5

  # core
  core_analytics:
    path: ../../core/core_analytics
  core_storage:
    path: ../core_storage
  core_environment:
    path: ../core_environment

  # library
  service_locator:
    path: ../../library/service_locator
  manga_service_drift:
    path: ../../library/manga_service_drift

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
