name: manga_service_drift
description: "A new Flutter project."
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.7.2 <4.0.0"
  flutter: ">=3.29.3"

dependencies:
  flutter:
    sdk: flutter
  drift: ^2.19.1+1
  drift_flutter: ^0.2.0
  path_provider: ^2.1.5
  sqlite3: ^2.4.5
  sqlite3_flutter_libs: ^0.5.0
  uuid: ^4.5.1
  path: ^1.9.0
  equatable: ^2.0.5
  drift_db_viewer: ^2.1.0
  collection: ^1.16.0
  rxdart: ^0.27.7
  universal_io: ^2.2.2
  http_cache_core: ^1.1.1
  file: ^7.0.0
  meta: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  flutter_lints: ^5.0.0
  drift_dev: ^2.19.1
