name: Build Application

on:
  # ref: https://docs.github.com/en/actions/reference/workflows-and-actions/events-that-trigger-workflows#pull_request
  pull_request:
    types: [opened, reopened, synchronize]
  # ref: https://docs.github.com/en/actions/reference/workflows-and-actions/events-that-trigger-workflows#push
  push:
    branches:
      - 'master'

jobs:
  build:
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: web
            os: ubuntu-latest
            path: build/web
          - platform: macos
            os: macos-15
            path: build/macos/Build/Products/Release/mangastash.app
          - platform: windows
            os: windows-latest
            path: build/windows/x64/runner/Release/mangastash.exe
          - platform: linux
            os: ubuntu-latest
            path: build/linux/x64/release/bundle/mangastash
#          - platform: ipa
#            os: macos-latest
#            path: build/ios/ipa
          - platform: apk
            os: ubuntu-latest
            path: build/app/outputs/apk/release/app-release.apk
    runs-on: ${{ matrix.os }}
    steps:
      - name: 'Git Checkout'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
      - name: 'Install Linux Dependencies'
        if: ${{ matrix.platform == 'linux' }}
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
      - name: 'Install Java'
        uses: actions/setup-java@v2
        if: ${{ matrix.platform == 'apk' }}
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: 'Install Flutter'
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.8'
          # disable cache, ref: https://github.com/subosito/flutter-action/issues/350
          cache: false
      - name: 'Flutter Doctor'
        run: flutter doctor -v
      - name: 'Install Melos'
        run: flutter pub global activate melos 6.2.0
      - name: 'Bootstrap Workspace'
        run: melos bootstrap --verbose
      - name: 'Build Application'
        run: flutter build ${{ matrix.platform }}
      - name: 'Compress Directory'
        uses: somaz94/compress-decompress@v1
        if: ${{ matrix.platform == 'web' }}
        with:
          command: compress
          source: ${{ matrix.path }}
          format: zip
          dest: build
          destfilename: 'web'
      - name: 'Save Artifact Non Web'
        if: ${{ matrix.platform != 'web' }}
        id: upload_artifact_non_web
        uses: actions/upload-artifact@v4
        with:
          name: release-${{ matrix.platform }}
          path: ${{ matrix.path }}
      - name: 'Save Artifact Web'
        if: ${{ matrix.platform == 'web' }}
        id: upload_artifact_web
        uses: actions/upload-artifact@v4
        with:
          name: release-${{ matrix.platform }}
          path: ${{ matrix.path }}.zip
      - name: 'Find Comment'
        uses: peter-evans/find-comment@v3
        id: find_comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: ${{ matrix.platform }} Build Successful!
      - name: 'Create or Update Comment Non Web'
        if: ${{ matrix.platform != 'web' }}
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.find_comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          edit-mode: replace
          body: |
            ![badge]

            ${{ matrix.platform }} Build Successful!
            Link: ${{ steps.upload_artifact_non_web.outputs.artifact-url }}

            [badge]: https://img.shields.io/badge/Build_Success!-0d1117?style=for-the-badge&labelColor=3fb950&logo=data:image/svg%2bxml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNCAyNCIgd2lkdGg9IjI0IiBoZWlnaHQ9IjI0IiBmaWxsPSIjZmZmZmZmIj48cGF0aCBkPSJNMjEuMDMgNS43MmEuNzUuNzUgMCAwIDEgMCAxLjA2bC0xMS41IDExLjVhLjc0Ny43NDcgMCAwIDEtMS4wNzItLjAxMmwtNS41LTUuNzVhLjc1Ljc1IDAgMSAxIDEuMDg0LTEuMDM2bDQuOTcgNS4xOTVMMTkuOTcgNS43MmEuNzUuNzUgMCAwIDEgMS4wNiAwWiI+PC9wYXRoPjwvc3ZnPg==

      - name: 'Create or Update Comment Web'
        if: ${{ matrix.platform == 'web' }}
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.find_comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          edit-mode: replace
          body: |
            ![badge]

            ${{ matrix.platform }} Build Successful!
            Link: ${{ steps.upload_artifact_web.outputs.artifact-url }}

            [badge]: https://img.shields.io/badge/Build_Success!-0d1117?style=for-the-badge&labelColor=3fb950&logo=data:image/svg%2bxml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNCAyNCIgd2lkdGg9IjI0IiBoZWlnaHQ9IjI0IiBmaWxsPSIjZmZmZmZmIj48cGF0aCBkPSJNMjEuMDMgNS43MmEuNzUuNzUgMCAwIDEgMCAxLjA2bC0xMS41IDExLjVhLjc0Ny43NDcgMCAwIDEtMS4wNzItLjAxMmwtNS41LTUuNzVhLjc1Ljc1IDAgMSAxIDEuMDg0LTEuMDM2bDQuOTcgNS4xOTVMMTkuOTcgNS43MmEuNzUuNzUgMCAwIDEgMS4wNiAwWiI+PC9wYXRoPjwvc3ZnPg==

      - name: 'Send debug APK to telegram'
        if: ${{ matrix.platform == 'apk' }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_GROUP_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            Here is the debug APK for ${{ github.event_name }}
            Runner OS: ${{ runner.os }}
            Event: ${{ github.event_name }}
            Job ID: ${{ github.job }}
            Triggered by: ${{ github.actor }}
            Branch or TAG: ${{ github.head_ref || github.ref_name }}
            Commit SHA: ${{ github.sha }}
            Artifact URL is: ${{ steps.upload_artifact_non_web.outputs.artifact-url }}
